name: Render Mermaid

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  render:
    name: Render Mermaid Diagrams
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Render images for every Mermaid diagram in all Markdown files
        uses: nielsvaneck/render-md-mermaid@v2

      - name: Commit rendered png and svg files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "*.svg *.png"
          commit_message: "docs: automatically rendered mermaid diagrams"
